repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: no-commit-to-branch
        args: [--branch, main, --branch, develop]

  - repo: local
    hooks:
      - id: golangci-lint-fix
        name: golangci-lint fix
        entry: golangci-lint run --fix
        language: system
        types: [go]
        pass_filenames: false
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.3
    hooks:
      - id: prettier
        types_or:
          - yaml
          - json
