basePath: /
definitions:
  dto.ConnectRequest:
    properties:
      player_name:
        type: string
      session_uuid:
        type: string
    type: object
  dto.CreateRequest:
    properties:
      rules:
        $ref: "#/definitions/dto.Rules"
      seed:
        type: integer
    type: object
  dto.DisconnectRequest:
    properties:
      player_uuid:
        type: string
      session_uuid:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.MakeMoveRequest:
    properties:
      mark_pos:
        $ref: "#/definitions/geometry.Point"
      player_uuid:
        type: string
      session_uuid:
        type: string
    type: object
  dto.Player:
    properties:
      mark:
        type: string
      name:
        type: string
      uuid:
        type: string
    type: object
  dto.Rules:
    properties:
      board_height:
        type: integer
      board_width:
        type: integer
      win_length:
        type: integer
    type: object
  dto.SessionResponse:
    properties:
      board:
        items:
          type: string
        type: array
      players:
        items:
          $ref: "#/definitions/dto.Player"
        type: array
      session_uuid:
        type: string
      state:
        type: string
      winner:
        type: string
    type: object
  dto.StartRequest:
    properties:
      player_uuid:
        type: string
      session_uuid:
        type: string
    type: object
  geometry.Point:
    properties:
      x:
        type: integer
      "y":
        type: integer
    type: object
host: localhost:12121
info:
  contact: {}
  description: Tic-Tac-Toe Game API
  title: Tic-Tac-Toe API
  version: "1.0"
paths:
  /game/{session_id}/connect:
    post:
      parameters:
        - description: Session ID
          in: path
          name: session_id
          required: true
          type: string
        - description: Player's data
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/dto.ConnectRequest"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/dto.SessionResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/dto.ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/dto.ErrorResponse"
      summary: Connect a Player
      tags:
        - game
  /game/{session_id}/disconnect:
    post:
      parameters:
        - description: Session ID
          in: path
          name: session_id
          required: true
          type: string
        - description: Player's data
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/dto.DisconnectRequest"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/dto.SessionResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/dto.ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/dto.ErrorResponse"
      summary: Disconnect a Player
      tags:
        - game
  /game/{session_id}/move:
    post:
      parameters:
        - description: Session ID
          in: path
          name: session_id
          required: true
          type: string
        - description: Move data
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/dto.MakeMoveRequest"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/dto.SessionResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/dto.ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/dto.ErrorResponse"
      summary: Make a Move
      tags:
        - game
  /game/{session_id}/start:
    post:
      parameters:
        - description: Session ID
          in: path
          name: session_id
          required: true
          type: string
        - description: Player's data
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/dto.StartRequest"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/dto.SessionResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/dto.ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/dto.ErrorResponse"
      summary: Start a Game
      tags:
        - game
  /game/create:
    post:
      parameters:
        - description: Game params
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/dto.CreateRequest"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/dto.SessionResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/dto.ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/dto.ErrorResponse"
      summary: Create a Game
      tags:
        - game
swagger: "2.0"
